### ISSUE TITLE
Text selection in /try does not work in firefox

### ISSUE THREAD

**Issue by antoineMoPa** [nullshape/nullshape.js#1]
We can't select text unless there is a bug in our code.

Under chromium, it works fine though.

**Comment by alexadam** [comment]
I tested it in both firefox & chrome, latest versions, on linux (ubuntu) but I can't reproduce...

![pp22](https://cloud.githubusercontent.com/assets/1687725/16722130/4d2d412c-474d-11e6-9cb1-444a91893872.png)

**Comment by antoineMoPa** [comment]
I just tried with the same laptop / browser / code and I can't reproduce either! I guess I did not have the latest version in my browser yesterday.

**Comment by alexadam** [comment]
@antoineMoPa  Since you are the most active user I've had on this project :) I'm curious what do you think about it. I made 'nullshape' because I want some tools to make it easier,faster and intuitive (from my point of view) to generate graphics.  Any feedback is welcome! Thanks.

**Comment by antoineMoPa** [comment]
The first thing that comes to my mind is that you should catch JS errors and show them so that we can see what's wrong with our code without starting the browser inspector/console.

Something like:

```
try{
    // Your evaluation code 
} catch (e) {
    put_e_in_some_div_somewhere(e);
}
```

**Comment by antoineMoPa** [comment]
Second thing, but for dynamic-ui:

If I understand well, the dynamic UI starts when you press middle mouse button (am I right ?), this makes it hard to popup on a laptop. I would prefer on control+click (but you can keep both control+click and middle-mouse-button) And you should write that somewhere in your landing page/editor: Pop up this tool up by doing 'x'.

**Comment by alexadam** [comment]
I'll add try/catch and some error messages in one of the next iterations

The dynamic Ui starts when "long" left click (click and hold for ~ .5 sec) or when you press Ctrl + ~  -> after you place the cursor on the underlined items 

Thanks!

**Comment by alexadam** [comment]
- I'll document how use the api & the pop-up - as soon as I have some time... this is one of the reasons I didn't upload the source

Here is a glitch app I made with the the same dynamic Ui: https://github.com/alexadam/glitch-studio

**Comment by antoineMoPa** [comment]
Ok, once you know it is "long click", it works fine :+1:
